# Branches that trigger a build on commit
trigger:
- main
- main-vs-deps
- release/*
- features/*
- demos/*

# Branches that trigger builds on PR
pr:
- main
- main-vs-deps
- release/*
- features/*
- demos/*

jobs:
- job: VS_Integration_Debug_32
  pool:
    name: $(poolName)
    demands: ImageOverride -equals $(queueName)
  timeoutInMinutes: 135
  condition: ne(variables['Build.Reason'], 'PullRequest')
  steps:
    - template: eng/pipelines/test-integration-job.yml
      parameters:
        configuration: 'Debug'
        oop64bit: false
        lspEditor: false

- job: VS_Integration_Debug_64
  pool:
    name: $(poolName)
    demands: ImageOverride -equals $(queueName)
  timeoutInMinutes: 135
  steps:
    - template: eng/pipelines/test-integration-job.yml
      parameters:
        configuration: 'Debug'
        oop64bit: true
        lspEditor: false

- job: VS_Integration_Release_32
  pool:
    name: $(poolName)
    demands: ImageOverride -equals $(queueName)
  timeoutInMinutes: 135
  steps:
    - template: eng/pipelines/test-integration-job.yml
      parameters:
        configuration: 'Release'
        oop64bit: false
        lspEditor: false

- job: VS_Integration_Release_64
  pool:
    name: $(poolName)
    demands: ImageOverride -equals $(queueName)
  timeoutInMinutes: 135
  condition: ne(variables['Build.Reason'], 'PullRequest')
  steps:
    - template: eng/pipelines/test-integration-job.yml
      parameters:
        configuration: 'Release'
        oop64bit: true
        lspEditor: false
